spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name:  energyplus

  datasource:
    url:  jdbc:oracle:thin:@112.221.156.34:12345:XE
    username:  KH15_LSM
    password: KH1234
    driver-class-name:  oracle.jdbc.driver.OracleDriver
  profiles:
    include: private
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000

server:
  port:  80


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.kh.ecolog.qna.model.vo,com.kh.ecolog.qna.model.dto, com.kh.ecolog.notice.model.dto, com.kh.ecolog.token.vo, com.kh.ecolog.challenge.model.dto, com.kh.ecolog.member.model.dto,  com.kh.ecolog.market.model.dto, com.kh.ecolog.challenge.model.vo.Challenge, com.kh.ecolog.market.board.model.dto, com.kh.ecolog.market.comment.model.dto, com.kh.ecolog.market.reply.model.dto, com.kh.ecolog.market.report.model.dto